### PR TITLE
Adds new_from_memory method

### PR DESCRIPTION
**Pull request by ankane**
Adds support for loading images from a binary string of pixel data. A few notes:

- Based on the [same function](https://github.com/libvips/pyvips/blob/b0a151af0e0c5d2a248009d148f4484b4344db6f/pyvips/vimage.py#L314) in pyvips
- Runs the GC in the test to confirm memory isn't freed (the test fails when the reference code is removed)
- Uses `send` to call a private function (could also have a public function named `_references` if that's preferred)

Also wanted to get your thoughts on having it accept a `FFI::Pointer` object, which would be useful for data that's already allocated (for performance).

### CODE REVIEW

**Comment by jcupitt** [comment]
Hi @ankane,

This is useful thing to put in, but I don't think your solution will work, unfortunately. It's making a relationship like this:

```
Ruby Image instance (a)
   + --> reference to FFI::MemoryPointer (b), released when (a) is GCd
   + --> reference to VipsObject (c), unreffed when (a) is finalized.
            + --> pointer to (b) but does not hold a ref to it
```

So (c) is using memory area (b), but the lifetime of (b) is controlled by (a). If (a) goes before (c), you'll get a crash.

There are two solutions:

1. Easy: use `vips_image_new_from_memory_copy()` instead. This will take a copy of the memory area, and libvips will own and free that copy. You don't need to keep track of `references` in Ruby, but you will have the copy overhead.
2. Harder: objects should inherit `references`. Every time you make one object from another in ruby-vips, you need to copy over the `references` list from the priors. 

In fact 2. isn't so bad -- it's just some extra code in `Operation::call`. pyvips does it here:

https://github.com/libvips/pyvips/blob/master/pyvips/voperation.py#L246

You could make it a bit neater in Ruby. A set container would be better, since you need quick lookup by value. There's already a `@references` member on Vips::Object.

**Comment by jcupitt** [comment]
Sure, a version that can skip the copy would be fantastic. pyvips has this.

**Comment by ankane** [comment]
Thanks @jcupitt, I agree skipping the copy would be better. Will work in that direction.

**Comment by ankane** [comment]
Take 2

**Comment by jcupitt** [comment]
That looks much better. I think you can remove the copy now and just save a reference to the `data` object.

I would add a second method, `new_from_memory_copy`, that just calls the libvips method and lets it handle memory lifetime.

**Comment by ankane** [comment]
Added a `new_from_memory_copy` method and also allowed both methods to accept an `FFI::Pointer` object.

What do you mean about saving the reference to the `data` object?

**Comment by jcupitt** [comment]
I think your `new_from_memory` method could just be:

```ruby
    def self.new_from_memory data, width, height, bands, format
      format_number = GObject::GValue.from_nick BAND_FORMAT_TYPE, format
      vi = Vips::vips_image_new_from_memory data, data.bytesize, width, height, bands, format_number
      raise Vips::Error, "unable to make image from memory" if vi.null?
      image = new(vi)

      # keep a secret ref to the underlying object .. this reference will be
      # inherited by things that in turn depend on us, so the memory we are
      # using will not be freed
      image.references << data

      image
    end
```

ie. there's no need to allocate FFI memory and copy the data over, since you are keeping a reference to the original ruby object.

`new_from_memory_copy` is the same, except you don't need to save the reference since libvips will be doing the copy.

**Comment by ankane** [comment]
Awesome, didn't realize that was possible. It looks like `FFI::Pointer` doesn't have a `bytesize` method, so adapted it slightly.

**Comment by ankane** [comment]
Hmm, looks like one of the JRuby tests failed due to GC. https://travis-ci.org/github/libvips/ruby-vips/jobs/730184160

**Comment by jcupitt** [comment]
Ahhh, I've never used FFI on jruby, I can imagine it'd be different.

You don't need the string arg to `Vips::Error` if it follows a libvips library call, since `Error` will automatically grab the error message from libvips. So you can write:

```ruby
      vi = Vips::vips_image_new_from_memory data, size, width, height, bands, format_number
      raise Vips::Error if vi.null?
```

It reduces maintenance slightly if there are fewer error messages to keep up to date.

**Comment by jcupitt** [comment]
It's curious that test failed, you'd think it was one of the safer ones. I suppose you'll need to add a lot of `puts` and try to see where the array values are trashed.

**Comment by ankane** [comment]
Updated the error message.

I'm not sure it'll be an easy task to debug what's going on with JRuby FFI. What are your thoughts on adding a conditional for JRuby (code in the commit)?

**Comment by jcupitt** [comment]
It feels a bit ugly. It'#d be better to figure out the jruby issue if we can.

Is jruby tricky to set up? I've not tried. Is there a recommended idiot's guide?

**Comment by ankane** [comment]
If you use rvm or rbenv, you can install it in a single command just like MRI versions.

**Comment by ankane** [comment]
Separate from the JRuby FFI issue, after doing more testing, it looks like the `size` method returns the max signed int64 value for `FFI::Pointer`, whereas as `FFI::MemoryPointer` returns the bytesize.

```ruby
FFI::MemoryPointer.new(:uint8, 10).size # 10
FFI::Pointer.new(:uint8, address).size # 9223372036854775807
```

From what I can tell, there doesn't appear to be a way to specify the size for `FFI::Pointer`, so I've removed support for passing pointers from the PR.

While it won't be officially supported, users can still pass pointers if they specify the size.

```ruby
data = FFI::Pointer.new(address)
data.define_singleton_method(:bytesize) do
  1234
end
```

**Comment by jcupitt** [comment]
Sorry, I took my eye off the ball here.

It looks fine -- let's merge and push 2.0.18 in a few days.

Thank you very much for working on this nice improvement!

**Comment by ankane** [comment]
Thanks @jcupitt. Just noticed the last commit removing the pointer stuff broke JRuby.

I can submit a PR to fix that specifically, or to support all pointers with a check to make sure they're bounded (also made a PR to FFI for a method to check if a pointer is bounded - https://github.com/ffi/ffi/pull/829). Let me know which you prefer.

**Comment by jcupitt** [comment]
Could you explain why `new_from_memory` broke, but `new_from_memory_copy` seems OK? They both appear to make the pointer in the same way.

A PR to fix this specific fail would be good in the short term. For a longer-term fix, perhaps we should step back and think again about pointers and datatypes.

(I've marked jruby as an allowed failure for now)

**Comment by jcupitt** [comment]
Oh honestly, my allow fail didn't work :( I'm so bad at yaml.

**Comment by ankane** [comment]
The `size` needed to be set before the JRuby conditional.

**Comment by jcupitt** [comment]
Ah of course, I was thinking of `new_from_buffer`, but that one is using the result of `write_to_buffer`.

**Pull request merged**
