### PR TITLE
 Do not use `env` for script shebangs

### PR DESCRIPTION
**Pull request by pvalena**
in example scripts.

### CODE REVIEW

**Comment by jcupitt** [comment]
I'm not dure what the best solution is here. I think something like this is necessary on macOS, where Apple ship a broken and horrible Ruby in `/usr/bin` and everyone uses homebrew's build in `/usr/local/bin`.

**Comment by pvalena** [comment]
We'll, you can always use containers :) f.e.
I agree that's a hard situation, but `/usr/bin/ruby` is the standard nonetheless.

**Comment by jcupitt** [comment]
Ah, you're right. Let the mac users moan heh.

**Comment by Nakilon** [comment]
I really wonder what's "broken and horrible" about Ruby on Alpine )
In fact I'm having a difficulty to compile my native extension on it and would love to know other pitfails.

**Comment by jcupitt** [comment]
Apple have (or had?) the broken Ruby. Alpine have their funny stack problem, but otherwise they should be OK, I think.

**Comment by Nakilon** [comment]
macOS have introduced the "sip protection" that made impossible to edit built-in Ruby code and install gems so people switched to rbenv.
Alpine compiles my gem in such way that when I require `.so` file it throws `symbol not found: ...` exceptions since Ruby 2.4. I'm yet to figure out how to fix.

**Pull request merged**
