### PR TITLE
[WIP] improve libname generation

### PR DESCRIPTION
**Pull request by jcupitt**
Library names for ffi vary by platform -- this patch adds a helper function which tries to generate the right format for mac / linux / win.

This works on ubuntu with dev packages installed. It needs testing on mac, win, and non-dev linux.

See https://github.com/libvips/ruby-vips/issues/176

### CODE REVIEW

**Comment by renchap** [comment]
I tested this branch on a `ruby:2.6-slim` container without `glib` / `libvips` header packages and it works fine (`libvips` package build using https://github.com/renchap/pkg-builders/tree/master/vips):
```
# ls -l /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0*
lrwxrwxrwx 1 root root      23 Jul 30 09:41 /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0 -> libglib-2.0.so.0.5800.3
-rw-r--r-- 1 root root 1166640 Jul 30 09:41 /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.5800.3
# ls -l /usr/lib/libvips*
-rw-r--r-- 1 root root  453562 Sep 20 15:28 /usr/lib/libvips-cpp.a
-rwxr-xr-x 1 root root    1173 Sep 20 15:28 /usr/lib/libvips-cpp.la
lrwxrwxrwx 1 root root      22 Sep 20 15:28 /usr/lib/libvips-cpp.so -> libvips-cpp.so.42.11.2
lrwxrwxrwx 1 root root      22 Sep 20 15:28 /usr/lib/libvips-cpp.so.42 -> libvips-cpp.so.42.11.2
-rwxr-xr-x 1 root root  286264 Sep 20 15:28 /usr/lib/libvips-cpp.so.42.11.2
-rw-r--r-- 1 root root 6375750 Sep 20 15:28 /usr/lib/libvips.a
-rwxr-xr-x 1 root root    1125 Sep 20 15:28 /usr/lib/libvips.la
lrwxrwxrwx 1 root root      18 Sep 20 15:28 /usr/lib/libvips.so -> libvips.so.42.11.2
lrwxrwxrwx 1 root root      18 Sep 20 15:28 /usr/lib/libvips.so.42 -> libvips.so.42.11.2
-rwxr-xr-x 1 root root 4163912 Sep 20 15:28 /usr/lib/libvips.so.42.11.2
# bundle exec rake spec
/usr/local/bin/ruby -I/usr/local/bundle/gems/rspec-core-3.8.2/lib:/usr/local/bundle/gems/rspec-support-3.8.2/lib /usr/local/bundle/gems/rspec-core-3.8.2/exe/rspec spec/image_spec.rb spec/vips_spec.rb
.....................................................................

Finished in 0.68627 seconds (files took 0.16583 seconds to load)
69 examples, 0 failures
```

On macOS with `libvips` from Homebrew:
```
renchap@Ghanima dev/ruby-vips (fix-libname) » ls -l /usr/local/lib/libvips*
lrwxr-xr-x  1 renchap  admin  45 Sep 17 14:54 /usr/local/lib/libvips-cpp.42.dylib -> ../Cellar/vips/8.8.3/lib/libvips-cpp.42.dylib
lrwxr-xr-x  1 renchap  admin  38 Sep 17 14:54 /usr/local/lib/libvips-cpp.a -> ../Cellar/vips/8.8.3/lib/libvips-cpp.a
lrwxr-xr-x  1 renchap  admin  42 Sep 17 14:54 /usr/local/lib/libvips-cpp.dylib -> ../Cellar/vips/8.8.3/lib/libvips-cpp.dylib
lrwxr-xr-x  1 renchap  admin  41 Sep 17 14:54 /usr/local/lib/libvips.42.dylib -> ../Cellar/vips/8.8.3/lib/libvips.42.dylib
lrwxr-xr-x  1 renchap  admin  34 Sep 17 14:54 /usr/local/lib/libvips.a -> ../Cellar/vips/8.8.3/lib/libvips.a
lrwxr-xr-x  1 renchap  admin  38 Sep 17 14:54 /usr/local/lib/libvips.dylib -> ../Cellar/vips/8.8.3/lib/libvips.dylib

renchap@Ghanima dev/ruby-vips (fix-libname) » bundle exec rake spec  
/Users/renchap/.rbenv/versions/2.6.4/bin/ruby -I/Users/renchap/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.2/lib:/Users/renchap/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/rspec-support-3.8.2/lib /Users/renchap/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.2/exe/rspec spec/image_spec.rb spec/vips_spec.rb
.....................................................................

Finished in 0.79671 seconds (files took 0.29773 seconds to load)
69 examples, 0 failures
```

**Comment by jcupitt** [comment]
OK! Thanks @renchap, let's merge.

**Comment by afcapel** [comment]
Any chance to get a new version published to rubygems with this change?

**Comment by jcupitt** [comment]
Thanks for the reminder -- 2.0.16 pushed.

**Comment by afcapel** [comment]
Awesome, thanks!

**Pull request merged**
